version: "3.4"

services:
  serverless-search:
    container_name: serverless-search
    image: appbaseio/serverless-search:8.5.0.alpha
    restart: always
    volumes:
      - serverless-search-data:/serverless-search-data
    ports:
      - 8000:8000
    depends_on:
      - zinc
    environment:
      - ZINC_CLUSTER_URL=http://appbase:ComplexPass#123!@localhost:4080
      - JWT_RSA_PUBLIC_KEY_LOC=sample/rsa-public
      - USERNAME=foo
      - PASSWORD=bar
      - SET_SNIFFING=false
      - APPBASE_ID=${APPBASE_ID}
      - LICENSE_KEY=${OFFLINE_APPBASE_LICENSE_KEY}
  zinc:
    container_name: zinc
    image: public.ecr.aws/zinclabs/zinc:latest
    restart: always
    ports:
      - 4080:4080
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=appbase
      - ZINC_FIRST_ADMIN_PASSWORD=ComplexPass#123!
    volumes:
      - ./zinc-data:/data
  nginx:
    container_name: appbase_nginx
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./reactivesearch-logo.svg:/etc/nginx/html/reactivesearch-logo.svg
      - ./nginx/certs:/etc/ssl/certs/
      - ./nginx/error.html:/etc/nginx/html/50x.html
      - www:/var/www/html
    ports:
      - 80:80
      - 443:443
    profiles:
      - nginx
  fluentbit:
    image: fluent/fluent-bit:1.9.4
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - serverless-search
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parser.conf:/fluent-bit/etc/parser.conf
      - serverless-search-data:/serverless-search-data

volumes:
  serverless-search-data:
    external: false
    name: serverless-search-data
  www:
    external: false
    name: www
  zinc-data:
    external: false
    name: zinc-data
