version: "3.4"

services:
  serverless-search:
    container_name: serverless-search
    image: appbaseio/serverless-search:8.4.0
    restart: always
    volumes:
      - serverless-search-data:/serverless-search-data
    ports:
      - 8000:8000
  nginx:
    container_name: appbase_nginx
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./reactivesearch-logo.svg:/etc/nginx/html/reactivesearch-logo.svg
      - ./nginx/certs:/etc/ssl/certs/
      - ./nginx/error.html:/etc/nginx/html/50x.html
      - www:/var/www/html
    ports:
      - 80:80
      - 443:443
  fluentbit:
    image: fluent/fluent-bit:1.9.4
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - serverless-search
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parser.conf:/fluent-bit/etc/parser.conf
      - serverless-search-data:/serverless-search-data

volumes:
  serverless-search-data:
    external: false
    name: serverless-search-data
  www:
    external: false
    name: www