name: build binary
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: building binaries for eaas deployments
        uses: appleboy/ssh-action@master
        env:
          VERSION: ${{ github.event.release.tag_name }}
        with:
          host: ${{ secrets.GCLOUD_BUILD_HOST }}
          username: ${{ secrets.GCLOUD_BUILD_USERNAME }}
          key: ${{ secrets.GCLOUD_BUILD_KEY }}
          port: 22
          timeout: 3600s
          command_timeout: 3600s
          envs: VERSION
          script: |
            sh sls-build.sh ${VERSION} feat/true-sls

  send-packer-event:
    name: Send Packer Event
    needs: build
    uses: ./.github/workflows/build-image.yml
    with:
      ref: ${{ github.ref }}
    secrets:
      token: ${{ secrets.TOKEN }}
